// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidf8AIPhOeUmWoWexKG4FjxVJtf5f3FI',
    appId: '1:474365592853:web:983968a8301766ce9a151c',
    messagingSenderId: '474365592853',
    projectId: 'chat-app-a8f22',
    authDomain: 'chat-app-a8f22.firebaseapp.com',
    storageBucket: 'chat-app-a8f22.firebasestorage.app',
    measurementId: 'G-8X6SGLGP3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrN8PfcfFNvTeOh9uFha1vU2oDzmCx86g',
    appId: '1:474365592853:android:f9923e1e769ce5879a151c',
    messagingSenderId: '474365592853',
    projectId: 'chat-app-a8f22',
    storageBucket: 'chat-app-a8f22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMM9WlbZle2NvCA8dY6TTShWXe6XT0qZY',
    appId: '1:474365592853:ios:97593a944b9a9c7c9a151c',
    messagingSenderId: '474365592853',
    projectId: 'chat-app-a8f22',
    storageBucket: 'chat-app-a8f22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
